# Define the sample names
# samples: ["Unassigned"]

# Working directory path
data_dir: "/mnt/md1200/epfl_sber/massimo/ChapterI/EUCI_MG/selection_inference/sbusi/clusters"

# Path to results directory
results_dir: "/mnt/md1200/epfl_sber/massimo/ChapterI/EUCI_MG/selection_inference/sbusi/clusters/results"

# Path to directory with KEGG fasta files
kfasta_dir: "/mnt/md1200/epfl_sber/massimo/ChapterI/EUCI_MG/selection_inference/sbusi"

# Path to DIAMOND database
diamond:
  db: "/mnt/esb-storage-01/nr_trembl/nr_uniprot_trembl.dmnd"
  threads: 48

## BBMAP ##
bbmap:
  mem: "1g"

## MAFFT ##
mafft:
  threads: 4
