# Path to data folder
data_dir: "/mnt/esb-storage-01/NOMIS/refseq/complete_prokaryotes/genbank/bacteria"

# Path to results folder
results_dir: "/mnt/data/sbusi/euci/results"

# Path to Conda environments:
env_dir: "/mnt/data/sbusi/euci/envs"

# Path to auxilliary scripts
scripts_dir: "/mnt/data/sbusi/euci/scripts"

# Path to databases
database_dir: "/mnt/esb-storage-01/NOMIS/databases"

# ESB-storage-01
esb-storage-01:
  path: "/mnt/esb-storage-01/NOMIS/refseq/complete_prokaryotes"

################################
# Prokka
prokka:
  threads: 12
  path: "/mnt/data/sbusi/euci/.snakemake/conda/34fca334/lib/site_perl/5.26.2"
  blast: "/mnt/data/sbusi/euci/.snakemake/conda/9654cb14/bin"

################################
# Prodigal
prodigal:
  threads: 4
  path: "/mnt/data/sbusi/euci/.snakemake/conda/cdaed2ee/lib/5.26.2"

################################
# BLAST
blast:
  db: "/mnt/data/sbusi/euci/RPROTDB/RPDB"
  max_hits: 1
  threads: 6

################################
# HMMER - for cold adapatation genes
hmmer:
  CAGhmm: "/mnt/esb-storage-01/NOMIS/databases/merged_cold_adaptation_genes.hmm"
  threads: 4
