# Path to data folder
data_dir: "/mnt/esb-storage-01/NOMIS/refseq/complete_prokaryotes/genbank/bacteria"

# Path to results folder
results_dir: "/mnt/data/sbusi/euci/results"

# Path to Conda environments:
env_dir: "/mnt/data/sbusi/euci/envs"

# Path to auxilliary scripts
scripts_dir: "/mnt/data/sbusi/euci/scripts"

# ESB-storage-01
esb-storage-01:
  path: "/mnt/esb-storage-01/NOMIS/refseq/complete_prokaryotes"

################################
# Prokka
prokka:
  threads: 12
  path: "/mnt/data/sbusi/euci/.snakemake/conda/34fca334/lib/site_perl/5.26.2"
  blast: "/mnt/data/sbusi/euci/.snakemake/conda/9654cb14/bin"

################################
# Prodigal
prodigal:
  threads: 1
  path: "/mnt/data/sbusi/euci/.snakemake/conda/cdaed2ee/lib/5.26.2"
